### ISSUE TITLE
NoSuchKeyException: stacktrace getNullableValue

### ISSUE THREAD

**Issue by sibelius** [getsentry/react-native-sentry#487] opened 2018-10-02 21:28 UTC
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v10.7.0
6.4.1
├── @expo/react-native-action-sheet@1.1.2
├── @ptomasroos/react-native-multi-slider@0.0.14
├── date-fns@1.29.0
├── emoji-mart-native@0.3.0-beta
├── fbemitter@2.1.1
├── formik@1.3.0
├── hoist-non-react-statics@1.2.0
├── idx@2.4.0
├── intl@1.2.5
├── path-match@1.2.4
├── path-to-regexp@2.4.0
├── prop-types@15.6.2
├── query-string@4.3.4
├── react@16.5.0
├── UNMET PEER DEPENDENCY react-native@0.57.1
├── react-native-action-button@2.8.5
├── react-native-button@2.3.0
├── react-native-camera@1.0.2
├── react-native-camera-roll-picker@1.2.3
├── react-native-checkbox-field@2.0.2
├── react-native-code-push@5.4.2
├── react-native-collapsible@0.13.0
├── react-native-communications@2.2.1
├── react-native-device-info@0.17.4
├── react-native-document-picker@2.1.0
├── react-native-emoji@1.3.1
├── react-native-fabric@0.5.2
├── react-native-firebase@5.0.0
├── react-native-gifted-chat@0.4.3
├── react-native-globalize@1.2.4
├── react-native-i18n@2.0.15
├── react-native-icon-badge@1.1.3
├── react-native-image-crop@1.0.2 invalid
├── react-native-image-resizer@1.0.0
├── react-native-keyboard-aware-scroll-view@0.5.0
├── react-native-keyboard-spacer@0.4.1
├── react-native-linear-gradient@2.4.2
├── react-native-localization@0.1.32
├── react-native-looped-carousel@0.1.13
├── react-native-mime-types@2.2.1
├── react-native-modal-datetime-picker@6.0.0
├── react-native-picker-select@4.4.0
├── react-native-root-toast@3.0.1
├── react-native-sentry@0.39.0
├── react-native-simple-radio-button@2.7.3
├── react-native-slider@0.11.0
├── react-native-splash-screen@3.1.1
├── react-native-svg@6.5.2
├── react-native-svg-image@2.0.1
├── react-native-swipeable@0.6.0
├── react-native-swiper@1.5.13
├── react-native-tab-view@1.0.2
├── react-native-tableview-simple@0.17.5
├── react-navigation@2.11.2
├── react-redux@5.0.7
├── react-relay@1.5.0
├── recompose@0.27.1
├── redux@4.0.0
├── redux-actions@2.6.1
├── redux-logger@3.0.6
├── redux-persist@4.10.2
├── redux-saga@0.16.0
├── relay-commit-mutation-promise@1.0.1
├── styled-components@3.4.9
├── tcomb-form-native@0.6.19
├── url-parse@1.4.3
├── victory-native@30.4.0
└── yup@0.24.1
```

---
I have following issue:

```
com.facebook.react.bridge.NoSuchKeyException: stacktrace
10-02 18:25:49.745  5663  6598 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:135)
10-02 18:25:49.745  5663  6598 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:139)
10-02 18:25:49.745  5663  6598 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getMap(ReadableNativeMap.java:210)
10-02 18:25:49.745  5663  6598 E unknown:ReactNative: 	at io.sentry.RNSentryModule.captureEvent(RNSentryModule.java:260)
10-02 18:25:49.745  5663  6598 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
10-02 18:25:49.745  5663  6598 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
10-02 18:25:49.745  5663  6598 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
10-02 18:25:49.745  5663  6598 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
```

this happening when we got an error

**Comment by K-Leon** [comment] 2018-10-04 13:31
Same Issue for me

**Comment by christianclent** [comment] 2018-10-19 17:59
Same here. I'm developing on Linux and targeting Android. In my case, this was caused by a segment of code throwing an exception inside of a "setInterval" callback. It would be really nice if Sentry could deal with this case gracefully.

**Comment by ndiyansah** [comment] 2018-10-22 10:19
Same issue for me

**Comment by Kdrbyrz** [comment] 2018-10-25 13:31
Same issue for me.

**Comment by darioceccoli** [comment] 2019-05-31 16:37
In my case the issue is that `captureEvent` in`RNSentryModule.java`, `event.exception` doesn't contain `stacktrace`. I think the existence of `stacktrace` should be checked as most other keys.

I'm on `react-native-sentry` version `0.43.1`.

**Comment by MLDimitry** [comment] 2019-06-03 15:17
I made a PR based on @darioceccoli's comment that checks if stacktrace exists before accessing it.

https://github.com/getsentry/react-native-sentry/pull/594

**Comment by llostris** [comment] 2019-06-14 07:47
We're experiencing the same issue on 0.43.1. Can we please have somebody look at that PR?

**Comment by joaom182** [comment] 2019-06-14 16:54
The branch master needs to be published to NPM urgent! This issue is affecting in Android production code.

**Comment by tonyo** [comment] 2019-06-17 08:45
Version 0.43.2 was released with the fix.

**Closed by tonyo** 2019-06-17 08:45 UTC

**Comment by Victorams** [comment] 2019-08-12 17:01
Still getting it with version 0.43.2.

The error shows in Google's Android Vitals as

**com.facebook.react.bridge.NoSuchKeyException:** 
  at com.facebook.react.bridge.ReadableNativeMap.getNullableValue (ReadableNativeMap.java:137)
  at com.facebook.react.bridge.ReadableNativeMap.getNullableValue (ReadableNativeMap.java:141)
  at com.facebook.react.bridge.ReadableNativeMap.getMap (ReadableNativeMap.java:212)
  **at io.sentry.RNSentryModule.captureEvent (RNSentryModule.java:268)**
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:158)
  at com.facebook.react.bridge.queue.NativeRunnable.run (Native Method)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:29)
  at android.os.Looper.loop (Looper.java:214)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:232)
  at java.lang.Thread.run (Thread.java:764)

**Comment by rarira** [comment] 2020-01-16 03:16
still with 1.2.1 only on release build

I temporarily disabled sentry in android build because of random crash.

**Comment by libereducacao** [comment] 2020-01-17 13:59
I am getting the exact same error that @rarira is getting.

**Comment by psyzz** [comment] 2020-01-20 21:40
Same error occurs on android when the app is in background for like an hour and goes to foreground : 

```
01-20 22:33:59.245  4239  4356 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: frames
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:124)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:128)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getArray(ReadableNativeMap.java:168)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at io.sentry.RNSentryModule.sendEvent(RNSentryModule.java:320)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:907)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
01-20 22:33:59.245  4239  4356 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:784)

```

**Comment by chgsilva** [comment] 2020-01-21 12:27
I opened a new issue regarding `NoSuchKeyException: frames`
https://github.com/getsentry/sentry-react-native/issues/742
