### ISSUE TITLE
iOS build fails post linking

### ISSUE THREAD

**Issue by samratshekhar** [getsentry/react-native-sentry#111] opened 2017-06-20 06:33 UTC
I followed the documentation to add sentry to our project. Everything worked fine till linking. Post linking, when all the data regarding token, DSN and slug related info was captured, the iOS build started failing with the following issues:

<img width="787" alt="screen shot 2017-06-20 at 11 46 40 am" src="https://user-images.githubusercontent.com/25629471/27319398-e90d0ddc-55ae-11e7-8e93-2767afe12117.png">
<img width="413" alt="screen shot 2017-06-20 at 11 46 05 am" src="https://user-images.githubusercontent.com/25629471/27319439-180c67ae-55af-11e7-8351-680ec9369d42.png">

The logs clearly states that **RNSentry** has issues in imports. I'd like to state that the import for **RNSentry** in **AppDelegate** was not added by the linking and had to be added manually. 

Upon further investigation, it seems that xcode is trying to import React related files from two different locations:
1. from node modules (expected)
<img width="533" alt="screen shot 2017-06-20 at 11 51 59 am" src="https://user-images.githubusercontent.com/25629471/27319614-f54f3f6a-55af-11e7-8a27-c3860de53933.png">

2. build directory from the iOS project (unexpected)
<img width="502" alt="screen shot 2017-06-20 at 11 51 41 am" src="https://user-images.githubusercontent.com/25629471/27319642-157d2e14-55b0-11e7-9fd9-76fc02c48b67.png">

I've tried to tweak the header search paths for both our project as well as RNSentry, but to no avail. Any help or suggestion is appreciated!

**Comment by prithsharma** [comment] 2017-06-20 09:34
Facing the same error. `Redefinition of 'RCTRootViewSizeFlexiblity'`
RN 0.44.0
Although in my case, checking the file of previous definition and redefinition both shows the same file(checked this by seeing the `Previous definition was here` file, which is same as the file in which the build error is reported).

@HazAT any ideas?

**Comment by samratshekhar** [comment] 2017-06-20 12:42
Update.
FWIW, after removing the import for `<React/RCTRootView.h>` and consecutive method `+ (void)installWithRootView:(RCTRootView *)rootView;`, I was able to build successfully.

**Comment by HazAT** [comment] 2017-06-21 06:52
I will check that today and keep you posted.

**Comment by samratshekhar** [comment] 2017-06-21 09:45
@HazAT I tried to do a dry run with aforementioned hack, but the upload scripts doesn't seem to work. I can't see artifacts being uploaded to the Sentry console, and the crashes mention that Sentry cannot find dsym as well as jsbundle. I tried uploading both manually, after which Sentry stopped complaining about dsym, but the missing jsbundle issue still persists. So here are my questions:
- Auto-upload not working while building from xcode - This issue seems unrelated from the hack. Could you point out if I've missed something while setting up, leading to this issue.
- Sentry unable to resolve the path of jsbundle - Can this be anyway related to the hack or because of improper setup and hence related to the first question?

**Comment by HazAT** [comment] 2017-06-21 09:56
@samratshekhar Your two questions are related since your link step didn't go through, you have to change the react-native run script.
https://docs.sentry.io/clients/react-native/manual-setup/#build-steps
This should then upload the sourcemaps correctly and resolve your issue.

**Comment by samratshekhar** [comment] 2017-06-21 10:52
@HazAT sorry for the miscommunication. `react-native link` was successful, but the consecutive xcode build was not. Hence I had to remove the imports from RNSentry project and change the methods it exposes to build it successfully in xcode. Here are the results of linking, which looks alright:

<img width="630" alt="screen shot 2017-06-21 at 4 16 44 pm" src="https://user-images.githubusercontent.com/25629471/27380581-462a748e-569d-11e7-8e9e-ffc6edd46a1b.png">
<img width="601" alt="screen shot 2017-06-21 at 4 16 59 pm" src="https://user-images.githubusercontent.com/25629471/27380586-4ab5cf9e-569d-11e7-922e-4739a32f5b15.png">

The problem is even with these commands in place, there are no uploads initiated by xcode build.

**Comment by feiyingx** [comment] 2017-06-23 22:53
Build is also failing for me, but a different error, it complains about `env: node: No such file or directory`. Was able to run npm install and react-native link without issues. Fails when building to the iOS simulator.

RN: 0.45.1
Node: 7.10.0

Thanks!

![screen shot 2017-06-23 at 3 52 44 pm](https://user-images.githubusercontent.com/90781/27502857-15285ad2-582c-11e7-86a2-2d2fe29396c6.png)

**Comment by HazAT** [comment] 2017-06-26 06:23
@feiyingx Can you check if this is in you `PATH`?
`PATH=$PATH:/usr/local/bin`
It seems like Xcode isn't able to call `node`.
In the run script phase you can change the location of node if necessary 
`export NODE_BINARY=node`

**Comment by samratshekhar** [comment] 2017-06-29 13:09
@HazAT any update on the core issue of error with imports?

**Comment by HazAT** [comment] 2017-06-29 13:49
I am not able to reproduce this,
I've just tried it with a clean project:
```
react-native init AwesomeProject
cd AwesomeProject
yarn add react-native-sentry
react-native link react-native-sentry
react-native run-ios
```
Works!

Only thing that is different is your import
```
#if __has_include(<React/RNSentry.h>)
#import <React/RNSentry.h> // This is used for versions of react >= 0.40
#else
#import "RNSentry.h" // This is used for versions of react < 0.40
#endif
```

**Comment by HazAT** [comment] 2017-08-02 12:47
I will close this issue for now, it must be related to either not calling `react-native link react-native-sentry` or calling it too often.

**Closed by HazAT** 2017-08-02 12:47 UTC

**Comment by DanDance** [comment] 2017-08-14 10:13
Having exactly the same issue. Any updates?

**Comment by HazAT** [comment] 2017-08-15 08:20
Please make sure to make a clean build, also clear derived data.
And call `react-native unlink react-native-sentry` and then `react-native link react-native-sentry`

**Comment by DanDance** [comment] 2017-08-18 08:09
It's weird, but after couple links and unlinks (yes, unlink was the last one) it started to work...

**Comment by HazAT** [comment] 2017-08-18 08:34
We will look into this, since this should not happen no matter what.

**Comment by binwilly** [comment] 2017-10-24 23:41
Same issue like @feiyingx 

Node: 6.10.3 (with nvm)
react-native-sentry: "^0.29.0"

I was able to fix it with: 
`ln -s /Users/{user}/.nvm/versions/node/v6.10.3/bin/node /usr/local/bin/node`

Changing `export NODE_BINARY={path to node}` didn't work for me, I wondering if somewhere is /usr/local/bin hardcoded

**Comment by hugomosh** [comment] 2018-06-05 23:55
The link worked:
`ln -s $HOME/.nvm/versions/node/<node_version>/bin/node /usr/local/bin/node`
But it takes a lot of time to finish the custom shell scripts
