### ISSUE TITLE
413 while uploading the sourcemaps as I generate a release build

### ISSUE THREAD

**Issue by edualm** [getsentry/react-native-sentry#488] opened 2018-10-08 15:50 UTC
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

(Posting the output of `yarn list --depth=0` since `yarn` is used for this project.)

```
v10.10.0
6.4.1
yarn list v1.9.4
├─ @athletiscope/react-native-timepicker@0.0.2
├─ @babel/code-frame@7.0.0-beta.47
├─ @babel/core@7.0.0-beta.47
├─ @babel/generator@7.0.0-beta.47
├─ @babel/helper-annotate-as-pure@7.0.0-beta.47
├─ @babel/helper-builder-binary-assignment-operator-visitor@7.0.0-beta.47
├─ @babel/helper-builder-react-jsx@7.0.0-beta.47
├─ @babel/helper-call-delegate@7.0.0-beta.47
├─ @babel/helper-define-map@7.0.0-beta.47
├─ @babel/helper-explode-assignable-expression@7.0.0-beta.47
├─ @babel/helper-function-name@7.0.0-beta.47
├─ @babel/helper-get-function-arity@7.0.0-beta.47
├─ @babel/helper-hoist-variables@7.0.0-beta.47
├─ @babel/helper-member-expression-to-functions@7.0.0-beta.47
├─ @babel/helper-module-imports@7.0.0-beta.47
├─ @babel/helper-module-transforms@7.0.0-beta.47
├─ @babel/helper-optimise-call-expression@7.0.0-beta.47
├─ @babel/helper-plugin-utils@7.0.0-beta.47
├─ @babel/helper-regex@7.0.0-beta.47
├─ @babel/helper-remap-async-to-generator@7.0.0-beta.47
├─ @babel/helper-replace-supers@7.0.0-beta.47
├─ @babel/helper-simple-access@7.0.0-beta.47
├─ @babel/helper-split-export-declaration@7.0.0-beta.47
├─ @babel/helper-wrap-function@7.0.0-beta.47
├─ @babel/helpers@7.0.0-beta.47
├─ @babel/highlight@7.0.0-beta.47
├─ @babel/plugin-external-helpers@7.0.0-beta.47
├─ @babel/plugin-proposal-class-properties@7.0.0-beta.47
├─ @babel/plugin-proposal-object-rest-spread@7.0.0-beta.47
├─ @babel/plugin-proposal-optional-chaining@7.0.0-beta.47
├─ @babel/plugin-syntax-class-properties@7.0.0-beta.47
├─ @babel/plugin-syntax-dynamic-import@7.0.0-beta.47
├─ @babel/plugin-syntax-flow@7.0.0-beta.47
├─ @babel/plugin-syntax-jsx@7.0.0-beta.47
├─ @babel/plugin-syntax-nullish-coalescing-operator@7.0.0-beta.47
├─ @babel/plugin-syntax-object-rest-spread@7.0.0-beta.47
├─ @babel/plugin-syntax-optional-chaining@7.0.0-beta.47
├─ @babel/plugin-transform-arrow-functions@7.0.0-beta.47
├─ @babel/plugin-transform-async-to-generator@7.0.0-beta.47
├─ @babel/plugin-transform-block-scoping@7.0.0-beta.47
├─ @babel/plugin-transform-classes@7.0.0-beta.47
├─ @babel/plugin-transform-computed-properties@7.0.0-beta.47
├─ @babel/plugin-transform-destructuring@7.0.0-beta.47
├─ @babel/plugin-transform-exponentiation-operator@7.0.0-beta.47
├─ @babel/plugin-transform-flow-strip-types@7.0.0-beta.47
├─ @babel/plugin-transform-for-of@7.0.0-beta.47
├─ @babel/plugin-transform-function-name@7.0.0-beta.47
├─ @babel/plugin-transform-literals@7.0.0-beta.47
├─ @babel/plugin-transform-modules-commonjs@7.0.0-beta.47
├─ @babel/plugin-transform-object-assign@7.0.0-beta.47
├─ @babel/plugin-transform-parameters@7.0.0-beta.47
├─ @babel/plugin-transform-react-display-name@7.0.0-beta.47
├─ @babel/plugin-transform-react-jsx-source@7.0.0-beta.47
├─ @babel/plugin-transform-react-jsx@7.0.0-beta.47
├─ @babel/plugin-transform-regenerator@7.0.0-beta.47
├─ @babel/plugin-transform-shorthand-properties@7.0.0-beta.47
├─ @babel/plugin-transform-spread@7.0.0-beta.47
├─ @babel/plugin-transform-sticky-regex@7.0.0-beta.47
├─ @babel/plugin-transform-template-literals@7.0.0-beta.47
├─ @babel/plugin-transform-unicode-regex@7.0.0-beta.47
├─ @babel/register@7.0.0-beta.47
├─ @babel/template@7.0.0-beta.47
├─ @babel/traverse@7.0.0-beta.47
├─ @babel/types@7.0.0-beta.47
├─ @sentry/cli@1.36.1
├─ @sentry/wizard@0.11.1
├─ abbrev@1.1.1
├─ absolute-path@0.0.0
├─ accepts@1.3.5
├─ agent-base@2.1.1
├─ ajv@4.11.8
├─ ansi-escapes@3.1.0
├─ ansi-gray@0.1.1
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ ansi-wrap@0.1.0
├─ ansi@0.3.1
├─ anymatch@2.0.0
├─ appcenter-analytics@1.6.0
├─ appcenter-crashes@1.6.0
├─ appcenter-link-scripts@1.6.0
├─ appcenter@1.6.0
├─ aproba@1.2.0
├─ are-we-there-yet@1.1.4
├─ arr-diff@4.0.0
├─ arr-flatten@1.1.0
├─ arr-union@3.1.0
├─ array-differ@1.0.0
├─ array-filter@0.0.1
├─ array-map@0.0.0
├─ array-reduce@0.0.0
├─ array-uniq@1.0.3
├─ array-unique@0.3.2
├─ art@0.10.2
├─ asap@2.0.6
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ assign-symbols@1.0.0
├─ ast-types@0.11.3
├─ async-limiter@1.0.0
├─ async@2.6.0
├─ asynckit@0.4.0
├─ atob@2.1.0
├─ aws-sign2@0.6.0
├─ aws4@1.7.0
├─ babel-code-frame@6.26.0
├─ babel-core@6.26.0
├─ babel-generator@6.26.1
├─ babel-helper-builder-react-jsx@6.26.0
├─ babel-helper-call-delegate@6.24.1
├─ babel-helper-define-map@6.26.0
├─ babel-helper-function-name@6.24.1
├─ babel-helper-get-function-arity@6.24.1
├─ babel-helper-hoist-variables@6.24.1
├─ babel-helper-optimise-call-expression@6.24.1
├─ babel-helper-regex@6.26.0
├─ babel-helper-replace-supers@6.24.1
├─ babel-helpers@6.24.1
├─ babel-messages@6.23.0
├─ babel-plugin-check-es2015-constants@6.22.0
├─ babel-plugin-external-helpers@6.22.0
├─ babel-plugin-syntax-class-properties@6.13.0
├─ babel-plugin-syntax-flow@6.18.0
├─ babel-plugin-syntax-jsx@6.18.0
├─ babel-plugin-syntax-object-rest-spread@6.13.0
├─ babel-plugin-syntax-trailing-function-commas@6.22.0
├─ babel-plugin-transform-class-properties@6.24.1
├─ babel-plugin-transform-es2015-arrow-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoped-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoping@6.26.0
├─ babel-plugin-transform-es2015-classes@6.24.1
├─ babel-plugin-transform-es2015-computed-properties@6.24.1
├─ babel-plugin-transform-es2015-destructuring@6.23.0
├─ babel-plugin-transform-es2015-for-of@6.23.0
├─ babel-plugin-transform-es2015-function-name@6.24.1
├─ babel-plugin-transform-es2015-literals@6.22.0
├─ babel-plugin-transform-es2015-modules-commonjs@6.26.0
├─ babel-plugin-transform-es2015-object-super@6.24.1
├─ babel-plugin-transform-es2015-parameters@6.24.1
├─ babel-plugin-transform-es2015-shorthand-properties@6.24.1
├─ babel-plugin-transform-es2015-spread@6.22.0
├─ babel-plugin-transform-es2015-sticky-regex@6.24.1
├─ babel-plugin-transform-es2015-template-literals@6.22.0
├─ babel-plugin-transform-es2015-unicode-regex@6.24.1
├─ babel-plugin-transform-es3-member-expression-literals@6.22.0
├─ babel-plugin-transform-es3-property-literals@6.22.0
├─ babel-plugin-transform-flow-strip-types@6.22.0
├─ babel-plugin-transform-object-rest-spread@6.26.0
├─ babel-plugin-transform-react-display-name@6.25.0
├─ babel-plugin-transform-react-jsx@6.24.1
├─ babel-plugin-transform-strict-mode@6.24.1
├─ babel-preset-es2015-node@6.1.1
├─ babel-preset-fbjs@2.1.4
├─ babel-preset-react-native@5.0.2
├─ babel-register@6.26.0
├─ babel-runtime@6.26.0
├─ babel-template@6.26.0
├─ babel-traverse@6.26.0
├─ babel-types@6.26.0
├─ babylon@7.0.0-beta.47
├─ balanced-match@1.0.0
├─ base-64@0.1.0
├─ base@0.11.2
├─ base64-js@1.2.3
├─ basic-auth@2.0.0
├─ bcrypt-pbkdf@1.0.1
├─ beeper@1.1.1
├─ big-integer@1.6.27
├─ block-stream@0.0.9
├─ blueimp-md5@2.10.0
├─ boom@2.10.1
├─ bplist-creator@0.0.7
├─ bplist-parser@0.1.1
├─ brace-expansion@1.1.11
├─ braces@1.8.5
├─ bser@2.0.0
├─ buffer-crc32@0.2.13
├─ buffer-from@1.0.0
├─ buffer@5.1.0
├─ builtin-modules@1.1.1
├─ bytes@3.0.0
├─ cache-base@1.0.1
├─ camelcase@4.1.0
├─ caseless@0.12.0
├─ chalk@1.1.3
├─ chardet@0.4.2
├─ charenc@0.0.2
├─ clamp@1.0.1
├─ class-utils@0.3.6
├─ cli-cursor@2.1.0
├─ cli-width@2.2.0
├─ cliui@3.2.0
├─ clone-stats@0.0.1
├─ clone@1.0.4
├─ co@4.6.0
├─ code-point-at@1.1.0
├─ code-push@2.0.5
├─ collection-visit@1.0.0
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ color-string@1.5.3
├─ color-support@1.1.3
├─ color@1.0.3
├─ combined-stream@1.0.6
├─ command-exists@1.2.2
├─ commander@2.15.1
├─ commondir@1.0.1
├─ component-emitter@1.2.1
├─ compressible@2.0.13
├─ compression@1.7.2
├─ concat-map@0.0.1
├─ concat-stream@1.6.2
├─ connect@3.6.6
├─ console-control-strings@1.1.0
├─ convert-source-map@1.5.1
├─ cookiejar@2.1.1
├─ copy-descriptor@0.1.1
├─ core-js@2.5.5
├─ core-util-is@1.0.2
├─ create-react-class@15.6.3
├─ create-react-context@0.2.2
├─ cross-spawn@5.1.0
├─ crypt@0.0.2
├─ cryptiles@2.0.5
├─ crypto-js@3.1.9-1
├─ dashdash@1.14.1
├─ data-uri-to-buffer@1.2.0
├─ dateformat@2.2.0
├─ debug@2.6.9
├─ decamelize@1.2.0
├─ decode-uri-component@0.2.0
├─ deep-extend@0.4.2
├─ deep-is@0.1.3
├─ define-property@0.2.5
├─ degenerator@1.0.4
├─ delayed-stream@1.0.0
├─ delegates@1.0.0
├─ denodeify@1.2.1
├─ depd@1.1.2
├─ destroy@1.0.4
├─ detect-indent@4.0.0
├─ detect-libc@1.0.3
├─ detect-newline@2.1.0
├─ dom-walk@0.1.1
├─ duplexer2@0.0.2
├─ ecc-jsbn@0.1.1
├─ ee-first@1.1.1
├─ encodeurl@1.0.2
├─ encoding@0.1.12
├─ envinfo@5.10.0
├─ error-ex@1.3.1
├─ errorhandler@1.5.0
├─ es6-promise@4.2.4
├─ es6-promisify@5.0.0
├─ escape-html@1.0.3
├─ escape-string-regexp@1.0.5
├─ escodegen@1.9.1
├─ esprima@3.1.3
├─ estraverse@4.2.0
├─ esutils@2.0.2
├─ etag@1.8.1
├─ event-target-shim@1.1.1
├─ eventemitter3@3.0.1
├─ exec-sh@0.2.1
├─ execa@0.7.0
├─ exit-hook@1.1.1
├─ expand-brackets@0.1.5
├─ expand-range@1.8.2
├─ extend-shallow@2.0.1
├─ extend@3.0.1
├─ external-editor@1.1.1
├─ extglob@0.3.2
├─ extsprintf@1.3.0
├─ fancy-log@1.3.2
├─ fast-levenshtein@2.0.6
├─ fb-watchman@2.0.0
├─ fbjs-scripts@0.8.2
├─ fbjs@0.8.16
├─ figures@2.0.0
├─ file-uri-to-path@1.0.0
├─ filename-regex@2.0.1
├─ fill-range@2.2.3
├─ finalhandler@1.1.0
├─ find-cache-dir@1.0.0
├─ find-up@2.1.0
├─ for-in@1.0.2
├─ for-own@0.1.5
├─ forever-agent@0.6.1
├─ form-data@2.3.2
├─ formidable@1.2.1
├─ fragment-cache@0.2.1
├─ fresh@0.5.2
├─ fs-extra@1.0.0
├─ fs.realpath@1.0.0
├─ fsevents@1.1.3
├─ fstream-ignore@1.0.5
├─ fstream@1.0.11
├─ ftp@0.3.10
├─ gauge@1.2.7
├─ get-caller-file@1.0.2
├─ get-stream@3.0.0
├─ get-uri@2.0.1
├─ get-value@2.0.6
├─ getpass@0.1.7
├─ glob-base@0.3.0
├─ glob-parent@2.0.0
├─ glob@7.1.2
├─ global@4.3.2
├─ globals@11.4.0
├─ glogg@1.0.1
├─ graceful-fs@4.1.11
├─ growly@1.3.0
├─ gud@1.0.0
├─ gulp-util@3.0.8
├─ gulplog@1.0.0
├─ har-schema@1.0.5
├─ har-validator@4.2.1
├─ has-ansi@2.0.0
├─ has-flag@3.0.0
├─ has-gulplog@0.1.0
├─ has-unicode@2.0.1
├─ has-value@1.0.0
├─ has-values@1.0.0
├─ hawk@3.1.3
├─ hoek@2.16.3
├─ hoist-non-react-statics@2.5.0
├─ home-or-tmp@2.0.0
├─ hosted-git-info@2.6.0
├─ http-errors@1.6.3
├─ http-proxy-agent@1.0.0
├─ http-signature@1.1.1
├─ https-proxy-agent@1.0.0
├─ i18n-js@3.0.3
├─ iconv-lite@0.4.21
├─ ieee754@1.1.11
├─ image-size@0.6.2
├─ imurmurhash@0.1.4
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ ini@1.3.5
├─ inquirer@1.1.2
├─ install@0.12.1
├─ invariant@2.2.4
├─ invert-kv@1.0.0
├─ ip@1.1.5
├─ is-accessor-descriptor@1.0.0
├─ is-arrayish@0.3.2
├─ is-buffer@1.1.6
├─ is-builtin-module@1.0.0
├─ is-data-descriptor@1.0.0
├─ is-descriptor@1.0.2
├─ is-dotfile@1.0.3
├─ is-equal-shallow@0.1.3
├─ is-extendable@0.1.1
├─ is-extglob@1.0.0
├─ is-finite@1.0.2
├─ is-fullwidth-code-point@2.0.0
├─ is-glob@2.0.1
├─ is-number@3.0.0
├─ is-odd@2.0.0
├─ is-plain-object@2.0.4
├─ is-posix-bracket@0.1.1
├─ is-primitive@2.0.0
├─ is-promise@2.1.0
├─ is-stream@1.1.0
├─ is-typedarray@1.0.0
├─ is-windows@1.0.2
├─ is-wsl@1.1.0
├─ isarray@0.0.1
├─ isexe@2.0.0
├─ isobject@3.0.1
├─ isomorphic-fetch@2.2.1
├─ isstream@0.1.2
├─ jest-docblock@23.0.1
├─ jest-haste-map@23.1.0
├─ jest-react-native@18.0.0
├─ jest-serializer@23.0.1
├─ jest-worker@23.0.1
├─ js-tokens@3.0.2
├─ jsbn@0.1.1
├─ jsesc@0.5.0
├─ json-schema@0.2.3
├─ json-stable-stringify@1.0.1
├─ json-stringify-safe@5.0.1
├─ json5@0.5.1
├─ jsonfile@2.4.0
├─ jsonify@0.0.0
├─ jsprim@1.4.1
├─ keymirror@0.1.1
├─ kind-of@3.2.2
├─ klaw@1.3.1
├─ lcid@1.0.0
├─ left-pad@1.3.0
├─ levn@0.3.0
├─ load-json-file@2.0.0
├─ locate-path@2.0.0
├─ lodash-es@4.17.8
├─ lodash._basecopy@3.0.1
├─ lodash._basetostring@3.0.1
├─ lodash._basevalues@3.0.0
├─ lodash._getnative@3.9.1
├─ lodash._isiterateecall@3.0.9
├─ lodash._reescape@3.0.0
├─ lodash._reevaluate@3.0.0
├─ lodash._reinterpolate@3.0.0
├─ lodash._root@3.0.1
├─ lodash.escape@3.2.0
├─ lodash.get@4.4.2
├─ lodash.isarguments@3.1.0
├─ lodash.isarray@3.0.4
├─ lodash.isequal@4.5.0
├─ lodash.keys@3.1.2
├─ lodash.pad@4.5.1
├─ lodash.padend@4.6.1
├─ lodash.padstart@4.6.1
├─ lodash.restparam@3.6.1
├─ lodash.template@3.6.2
├─ lodash.templatesettings@3.1.1
├─ lodash.throttle@4.1.1
├─ lodash@4.17.5
├─ loose-envify@1.3.1
├─ lru-cache@4.1.2
├─ make-dir@1.3.0
├─ makeerror@1.0.11
├─ map-age-cleaner@0.1.2
├─ map-cache@0.2.2
├─ map-visit@1.0.0
├─ mem@1.1.0
├─ merge-stream@1.0.1
├─ merge@1.2.0
├─ methods@1.1.2
├─ metro-babel-register@0.38.3
├─ metro-babel7-plugin-react-transform@0.38.3
├─ metro-cache@0.38.3
├─ metro-core@0.38.3
├─ metro-memory-fs@0.38.3
├─ metro-minify-uglify@0.38.3
├─ metro-resolver@0.38.3
├─ metro-source-map@0.38.3
├─ metro@0.38.3
├─ micromatch@2.3.11
├─ mime-db@1.33.0
├─ mime-types@2.1.18
├─ mime@1.6.0
├─ mimic-fn@1.2.0
├─ min-document@2.19.0
├─ minimatch@3.0.4
├─ minimist@1.2.0
├─ mixin-deep@1.3.1
├─ mkdirp@0.5.1
├─ moment@2.22.0
├─ morgan@1.9.0
├─ ms@2.0.0
├─ multipipe@0.1.2
├─ mute-stream@0.0.7
├─ nan@2.10.0
├─ nanomatch@1.2.9
├─ native-base-shoutem-theme@0.2.2
├─ native-base@2.8.0
├─ negotiator@0.6.1
├─ netmask@1.0.6
├─ next-frame@0.2.3
├─ nice-try@1.0.5
├─ node-fetch@1.7.3
├─ node-int64@0.4.0
├─ node-modules-regexp@1.0.0
├─ node-notifier@5.2.1
├─ node-pre-gyp@0.6.39
├─ nopt@4.0.1
├─ normalize-package-data@2.4.0
├─ normalize-path@2.1.1
├─ npm-run-path@2.0.2
├─ npmlog@2.0.4
├─ number-is-nan@1.0.1
├─ oauth-sign@0.8.2
├─ object-assign@4.1.1
├─ object-copy@0.1.0
├─ object-visit@1.0.1
├─ object.omit@2.0.1
├─ object.pick@1.3.0
├─ on-finished@2.3.0
├─ on-headers@1.0.1
├─ once@1.4.0
├─ onetime@2.0.1
├─ opn@3.0.3
├─ optimist@0.6.1
├─ optionator@0.8.2
├─ options@0.0.6
├─ os-homedir@1.0.2
├─ os-locale@2.1.0
├─ os-shim@0.1.3
├─ os-tmpdir@1.0.2
├─ osenv@0.1.5
├─ p-defer@1.0.0
├─ p-finally@1.0.0
├─ p-is-promise@1.1.0
├─ p-limit@1.2.0
├─ p-locate@2.0.0
├─ p-try@1.0.0
├─ pac-proxy-agent@2.0.0
├─ pac-resolver@3.0.0
├─ parse-glob@3.0.4
├─ parse-json@2.2.0
├─ parseurl@1.3.2
├─ pascalcase@0.1.1
├─ path-exists@3.0.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ path-parse@1.0.5
├─ path-to-regexp@1.7.0
├─ path-type@2.0.0
├─ pegjs@0.10.0
├─ performance-now@2.1.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ pirates@3.0.2
├─ pkg-dir@2.0.0
├─ plist@1.2.0
├─ posix-character-classes@0.1.1
├─ prelude-ls@1.1.2
├─ preserve@0.2.0
├─ pretty-format@4.3.1
├─ print-message@2.1.0
├─ private@0.1.8
├─ process-nextick-args@2.0.0
├─ process@0.5.2
├─ progress@2.0.0
├─ promise@7.3.1
├─ prop-types@15.6.1
├─ proxy-agent@2.2.0
├─ proxy-from-env@1.0.0
├─ pseudomap@1.0.2
├─ punycode@1.3.2
├─ q@1.5.1
├─ qs@6.5.1
├─ query-string@6.1.0
├─ querystring@0.2.0
├─ r2@2.0.1
├─ raf@3.4.0
├─ randomatic@1.1.7
├─ range-parser@1.2.0
├─ raven-js@3.27.0
├─ raw-body@2.3.2
├─ rc@1.2.6
├─ react-clone-referenced-element@1.0.1
├─ react-deep-force-update@1.1.1
├─ react-devtools-core@3.2.3
├─ react-lifecycles-compat@3.0.4
├─ react-native-android-location-services-dialog-box@2.4.4
├─ react-native-animatable@1.2.4
├─ react-native-auth0@1.2.2
├─ react-native-calendars@1.19.3
├─ react-native-code-push@5.3.2
├─ react-native-dismiss-keyboard@1.0.0
├─ react-native-drawer-layout-polyfill@1.3.2
├─ react-native-drawer-layout@1.3.2
├─ react-native-drawer@2.5.0
├─ react-native-easy-grid@0.2.0
├─ react-native-fab@1.0.6
├─ react-native-fetch-blob@0.10.8
├─ react-native-fs@2.9.11
├─ react-native-geolocation-service@1.0.4
├─ react-native-gps-state@0.0.2
├─ react-native-i18n@2.0.12
├─ react-native-icon@0.2.10
├─ react-native-image-crop-picker@0.19.3
├─ react-native-immediate-phone-call@1.0.0
├─ react-native-iphone-x-helper@1.0.3
├─ react-native-keyboard-aware-scroll-view@0.5.0
├─ react-native-mail@3.0.6
├─ react-native-modal-datetime-picker@4.13.0
├─ react-native-modal@5.4.0
├─ react-native-pdf@3.0.6
├─ react-native-pod@1.10.2
├─ react-native-print@0.4.0
├─ react-native-prompt-android@0.3.3
├─ react-native-push-notification@3.0.2
├─ react-native-restart@0.0.6
├─ react-native-safe-area-view@0.8.0
├─ react-native-sentry@0.39.0
├─ react-native-swipeout@2.3.3
├─ react-native-tab-view@0.0.77
├─ react-native-table-component@1.1.8
├─ react-native-uuid-generator@4.0.1
├─ react-native-vector-icons@4.6.0
├─ react-native-video-controls@2.2.1
├─ react-native-video@2.0.0
├─ react-native-wheel-picker-android@1.1.4
├─ react-native@0.56.0
├─ react-navigation-deprecated-tab-navigator@1.3.0
├─ react-navigation-drawer@0.4.3
├─ react-navigation-tabs@0.5.1
├─ react-navigation@2.9.0
├─ react-proxy@1.1.8
├─ react-redux@5.0.7
├─ react-timer-mixin@0.13.3
├─ react-transform-hmr@1.0.4
├─ react-tween-state@0.1.5
├─ react@16.4.1
├─ read-env@1.3.0
├─ read-pkg-up@2.0.0
├─ read-pkg@2.0.0
├─ readable-stream@2.3.6
├─ recursive-fs@0.1.4
├─ redux-persist-filesystem-storage@1.2.0
├─ redux-persist@5.9.1
├─ redux@3.7.2
├─ regenerate-unicode-properties@7.0.0
├─ regenerate@1.4.0
├─ regenerator-runtime@0.11.1
├─ regenerator-transform@0.12.3
├─ regex-cache@0.4.4
├─ regex-not@1.0.2
├─ regexpu-core@4.2.0
├─ regjsgen@0.4.0
├─ regjsparser@0.3.0
├─ remove-trailing-separator@1.1.0
├─ repeat-element@1.1.2
├─ repeat-string@1.6.1
├─ repeating@2.0.1
├─ replace-ext@0.0.1
├─ request@2.81.0
├─ require-directory@2.1.1
├─ require-main-filename@1.0.1
├─ resolve-url@0.2.1
├─ resolve@1.7.1
├─ restore-cursor@2.0.0
├─ ret@0.1.15
├─ rimraf@2.6.2
├─ rn-fetch-blob@0.10.11
├─ run-async@2.3.0
├─ rx-lite-aggregates@4.0.8
├─ rx-lite@4.0.8
├─ rx@4.1.0
├─ rxjs@6.3.3
├─ safe-buffer@5.1.1
├─ safe-regex@1.1.0
├─ safer-buffer@2.1.2
├─ sane@2.5.0
├─ sax@1.1.6
├─ semver@5.5.0
├─ send@0.16.2
├─ serialize-error@2.1.0
├─ serve-static@1.13.2
├─ set-blocking@2.0.0
├─ set-value@2.0.0
├─ setimmediate@1.0.5
├─ setprototypeof@1.1.0
├─ sha1@1.1.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ shell-quote@1.6.1
├─ shellwords@0.1.1
├─ signal-exit@3.0.2
├─ simple-plist@0.2.1
├─ simple-swizzle@0.2.2
├─ slash@1.0.0
├─ slide@1.1.6
├─ smart-buffer@1.1.15
├─ snapdragon-node@2.1.1
├─ snapdragon-util@3.0.1
├─ snapdragon@0.8.2
├─ sntp@1.0.9
├─ socks-proxy-agent@3.0.1
├─ socks@1.1.10
├─ source-map-resolve@0.5.1
├─ source-map-support@0.4.18
├─ source-map-url@0.4.0
├─ source-map@0.5.7
├─ sparkles@1.0.0
├─ spawn-sync@1.0.15
├─ spdx-correct@3.0.0
├─ spdx-exceptions@2.1.0
├─ spdx-expression-parse@3.0.0
├─ spdx-license-ids@3.0.0
├─ split-string@3.1.0
├─ sshpk@1.14.1
├─ stacktrace-parser@0.1.4
├─ static-extend@0.1.2
├─ statuses@1.5.0
├─ stream-buffers@2.2.0
├─ strict-uri-encode@2.0.0
├─ string_decoder@1.1.1
├─ string-width@2.1.1
├─ stringstream@0.0.5
├─ strip-ansi@3.0.1
├─ strip-bom@3.0.0
├─ strip-eof@1.0.0
├─ strip-json-comments@2.0.1
├─ superagent-proxy@1.0.3
├─ superagent@3.8.2
├─ supports-color@2.0.0
├─ symbol-observable@1.2.0
├─ tar-pack@3.4.1
├─ tar@2.2.1
├─ temp@0.8.3
├─ throat@4.1.0
├─ through@2.3.8
├─ through2@2.0.3
├─ thunkify@2.1.2
├─ time-stamp@1.1.0
├─ tmp@0.0.33
├─ tmpl@1.0.4
├─ to-fast-properties@2.0.0
├─ to-object-path@0.3.0
├─ to-regex-range@2.1.1
├─ to-regex@3.0.2
├─ tough-cookie@2.3.4
├─ trim-right@1.0.1
├─ tslib@1.9.3
├─ tunnel-agent@0.6.0
├─ tween-functions@1.2.0
├─ tweetnacl@0.14.5
├─ type-check@0.3.2
├─ typedarray-to-buffer@3.1.5
├─ typedarray@0.0.6
├─ ua-parser-js@0.7.17
├─ uglify-es@3.3.9
├─ uid-number@0.0.6
├─ ultron@1.0.2
├─ unicode-canonical-property-names-ecmascript@1.0.4
├─ unicode-match-property-ecmascript@1.0.4
├─ unicode-match-property-value-ecmascript@1.0.2
├─ unicode-property-aliases-ecmascript@1.0.4
├─ union-value@1.0.0
├─ unpipe@1.0.0
├─ unset-value@1.0.0
├─ urix@0.1.0
├─ url@0.11.0
├─ use@3.1.0
├─ utf8@2.1.2
├─ util-deprecate@1.0.2
├─ utils-merge@1.0.1
├─ uuid@3.0.1
├─ validate-npm-package-license@3.0.3
├─ vary@1.1.2
├─ verror@1.10.0
├─ vinyl@0.5.3
├─ walker@1.0.7
├─ watch@0.18.0
├─ whatwg-fetch@2.0.4
├─ which-module@2.0.0
├─ which@1.3.0
├─ wide-align@1.1.2
├─ wordwrap@1.0.0
├─ wrap-ansi@2.1.0
├─ wrappy@1.0.2
├─ write-file-atomic@1.3.4
├─ ws@1.1.5
├─ xcode@1.0.0
├─ xdate@0.8.2
├─ xmlbuilder@4.0.0
├─ xmldoc@0.4.0
├─ xmldom@0.1.27
├─ xpipe@1.0.5
├─ xregexp@4.0.0
├─ xtend@4.0.1
├─ y18n@3.2.1
├─ yallist@2.1.2
├─ yargs-parser@7.0.0
├─ yargs@9.0.1
└─ yazl@2.4.3

```

Config:

```
Sentry.config('https://...@sentry.io/...'}).install()
```

---
I have following issue:

Generating a release build for Android fails (I haven't tried iOS) as the sourcemaps can't be uploaded.

```
> Uploading source maps for release [project id]-1.20
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)


FAILURE: Build failed with an exception.

* Where:
Script '[path to project]/node_modules/react-native-sentry/sentry.gradle' line: 176
```

Trying to upload them manually also fails:

```
➜  android ✗ SENTRY_PROPERTIES=./sentry.properties ../node_modules/@sentry/cli/bin/sentry-cli releases --org [org name] --project [project name] files [project] upload-sourcemaps ../build/CodePush --rewrite                      
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
> Uploading source maps for release [project]
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)
```

**Steps to reproduce:**
- `./gradlew assembleRelease` under the `android` folder.

**Actual result:**
- The compilation fails and the sourcemap isn't uploaded to Sentry.

**Expected result:**
- The compilation to succeed and the sourcemap to be uploaded to Sentry.

I beleive this is because the sourcemap is too big, at around 66MB. Is there a way to reduce it? The actual JS bundle is only 2.5MB, so I assume it's because of the sourcemaps of the libraries? Is there any way I can generate a sourcemap without them?

Thanks in advance.

**Comment by se-bastiaan** [comment] 2018-11-04 23:59
This looks like a duplicate of #326

**Comment by HazAT** [comment] 2018-11-15 12:13
Thanks for reporting, adding this to the other issue.

**Closed by HazAT** 2018-11-15 12:13 UTC
