### ISSUE TITLE
setUserContext doesn't work

### ISSUE THREAD

**Issue by gaykov** [getsentry/react-native-sentry#314] opened 2017-12-20 08:47 UTC
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v7.8.0
4.2.0
...@0.1.0 ...
├── eslint@4.5.0
├── eslint-config-airbnb@15.1.0
├── eslint-plugin-jsx-a11y@6.0.2
├── eslint-plugin-react-native@3.0.1
├── react@16.0.0-alpha.12
├── react-native@0.46.4
├── react-native-camera@0.10.0
├── react-native-code-push@5.1.2-beta
├── react-native-communications@2.2.1
├── react-native-device-info@0.11.0
├── react-native-htmlview@0.12.0
├── react-native-i18n@2.0.5
├── react-native-linear-gradient@2.3.0
├── react-native-sentry@0.26.0
├── react-native-swiper@1.5.10
├── react-native-vector-icons@4.3.0
├── react-navigation@1.0.0-beta.11
├── react-redux@5.0.6
├── recompose@0.25.0
├── redux@3.7.2
├── redux-logger@3.0.6
├── redux-persist@4.8.3
├── redux-promise@0.5.3
└── redux-thunk@2.2.0
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
  logLevel: SentryLog.Verbose,
}).install();
```

---
I have following issue:

`setUserContext` doesn't work for me. After user login event in the app I call the `setUserContext` function:
```
Sentry.setUserContext({
    id: userId,
});
```

Then, in debug console I see
![image](https://user-images.githubusercontent.com/9068073/34198352-23e20168-e57b-11e7-8816-b9edf4e3ae9b.png)

But after any crash, on my Sentry dashboard, I see userId as an ip address.

**Comment by HazAT** [comment] 2017-12-20 08:52
Hey, so can you upgrade to the latest version.
I am pretty sure this bug has already been fixed, please be aware that in the latest version `0.32.0` uses the new @sentry/cli npm package, so you slightly have to adjust your build process.

But I think version `0.31.0` should also work.

**Comment by gaykov** [comment] 2017-12-20 09:00
@HazAT thank you for the prompt reply!

Just updated to the `0.31.0` version but it didn't help. Interesting thing that `setTagsContext` works and I see it in my Sentry dashboard's breadcrumbs log as
![image](https://user-images.githubusercontent.com/9068073/34198992-42fb38d8-e57d-11e7-8a41-988b4ee56e84.png)

But I don't see `setUserContext` there (but I still see it in my local Chrome console)

**Comment by gaykov** [comment] 2017-12-20 09:38
I've found that for some reasons it's losing the userContext after application reloading. If I do the following way:
1. Do user login and call setUserContext with user id (I see `setUserContext` in the logs)
2. Reload an application (with CMD+R in development mode)
3. Click some button to generate an exception

I don't get userId stored in the Sentry dashboard. Is it an expected behavior (I don't think so because it was working previously)?

It works if I do the following way:
1. Use `componentWillReceiveProps` in App component to determine when the state gets rehydrated from redux-persist
2. Call `setUserContext` once it's changed

**Comment by HazAT** [comment] 2017-12-20 10:02
@gaykov can you try to patch the `RNSentry.m` locally in you node_modules and see if it works:
https://github.com/getsentry/react-native-sentry/pull/315

**Comment by gaykov** [comment] 2017-12-20 10:24
@HazAT didn't help, I still see an ip address as a user identifier. And the error in Sentry dashboard looks different from others:
![image](https://user-images.githubusercontent.com/9068073/34202453-de0d5238-e588-11e7-91dd-27eb50c11bdf.png)

**Comment by HazAT** [comment] 2017-12-20 10:29
OK, there must is something weird going on in your setup.
I tried it locally and it works as expected in the example project we have 
https://github.com/getsentry/examples/tree/master/react-native

Can you link me to your source somehow because I am not really able to reproduce it?!

**Comment by HazAT** [comment] 2018-01-03 08:38
I will close this for now since I wasn't able to reproduce it. 
Please feel free to reopen it whenever you are able to provide a reproducible case.

**Closed by HazAT** 2018-01-03 08:38 UTC
