### ISSUE TITLE
Android Gradle deprecation - TaskInternal.executer

### ISSUE THREAD

**Issue by crobinson42** [getsentry/react-native-sentry#588] opened 2019-05-21 16:33 UTC
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

---
I have following issue:

During an Android release build with the latest `react-native@0.59` I see this in the logs:

```
The TaskInternal.executer property has been deprecated. This is scheduled to be removed in Gradle 5.0. There are better ways to re-use task logic, see https://docs.gradle.org/4.10.2/userguide/custom_tasks.html#sec:reusing_task_logic.
        at sentry_5mjg87nbsehw8dyhs15usfffm$_run_closure1$_closure6.doCall(/Users/willlyrob/projects/sscs/hhs2/node_modules/react-native-sentry/sentry.gradle:19)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

**Comment by gianpaj** [comment] 2019-06-06 08:13
looks like a duplicate of #397

**Closed** 2019-06-14 19:53 UTC
