### ISSUE TITLE
stacktrace problem in Android (Source code was not found for app:///[native code])

### ISSUE THREAD

**Issue by vincejah** [getsentry/react-native-sentry#136] opened 2017-07-05 07:08 UTC
when I try to make my Android app crash, I can see in the logcat the following:
```
 'Raven about to send:', { project: '164894',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:   logger: 'javascript',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:   platform: 'javascript',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:   request: {},
07-05 08:54:29.825 11948 11980 D ReactNativeJS:   exception: 
07-05 08:54:29.825 11948 11980 D ReactNativeJS:    { values: 
07-05 08:54:29.825 11948 11980 D ReactNativeJS:       [ { type: 'TypeError',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:           value: 'undefined is not a function (evaluating \'e.props.unknownProp()\')',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:           stacktrace: 
07-05 08:54:29.825 11948 11980 D ReactNativeJS:            { frames: 
07-05 08:54:29.825 11948 11980 D ReactNativeJS:               [ { filename: '[native code]',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   lineno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   colno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   function: '?',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   in_app: true },
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                 { filename: '[native code]',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   lineno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   colno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   function: 'forEach',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   in_app: true },
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                 { filename: '[native code]',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   lineno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   colno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   function: '?',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   in_app: true },
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                 { filename: '[native code]',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   lineno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   colno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   function: '?',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   in_app: true },
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                 { filename: '[native code]',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   lineno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   colno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   function: '?',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   in_app: true },
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                 { filename: '[native code]',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   lineno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   colno: null,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   function: '?',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:                   in_app: true } ] } } ] },
07-05 08:54:29.825 11948 11980 D ReactNativeJS:   culprit: '[native code]',
07-05 08:54:29.825 11948 11980 D ReactNativeJS:   timestamp: 1499237619.58,
07-05 08:54:29.825 11948 11980 D ReactNativeJS:   tags: { environment: 'production', react: true },
07-05 08:54:29.825 11948 11980 D ReactNativeJS:   extra: 
07-05 08:54:29.825 11948 11980 D ReactNativeJS:    { store: ...
```
And obviously, when I see my issue dashboard, there is a message saying:
`Source code was not found for app:///[native code]`

sourcemaps are built and uploaded to sentry using the installRelease command

setup:
- react-native 0.44.3
- react-native-sentry: 0.14.0

**Comment by HazAT** [comment] 2017-07-05 07:19
Hey, sorry about that.
I've just made a bugfix release `0.14.1` which resolves this issue.
Please upgrade :)

**Comment by vincejah** [comment] 2017-07-05 07:30
Thanks for your prompt response and fix. I've upgraded to 0.14.1. It works better, but I still get the error:
```'Raven about to send:', { project: '164894',
07-05 09:23:29.561 18030 18063 D ReactNativeJS:   logger: 'javascript',
07-05 09:23:29.561 18030 18063 D ReactNativeJS:   platform: 'javascript',
07-05 09:23:29.561 18030 18063 D ReactNativeJS:   request: {},
07-05 09:23:29.561 18030 18063 D ReactNativeJS:   exception: 
07-05 09:23:29.561 18030 18063 D ReactNativeJS:    { values: 
07-05 09:23:29.561 18030 18063 D ReactNativeJS:       [ { type: 'TypeError',
07-05 09:23:29.561 18030 18063 D ReactNativeJS:           value: 'undefined is not a function (evaluating \'e.props.unknownProp()\')',
07-05 09:23:29.561 18030 18063 D ReactNativeJS:           stacktrace: 
07-05 09:23:29.561 18030 18063 D ReactNativeJS:            { frames: 
07-05 09:23:29.561 18030 18063 D ReactNativeJS:               [ { filename: '[native code]',
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                   lineno: null,
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                   colno: null,
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                   function: '?',
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                   in_app: true },
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                 { filename: 'index.android.bundle',
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                   lineno: 338,
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                   colno: 925,
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                   function: 'value',
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                   in_app: true },
07-05 09:23:29.561 18030 18063 D ReactNativeJS:                 { filename: 'index.android.bundle',....
```

and the dashboard points at the last line of the file
`export default connect(mapStateToProps, mapDispatchToProps)(DebugScreen)` instead of the line of the button press event that fires the crash

**Comment by HazAT** [comment] 2017-07-05 07:40
Right, thats the same issue as https://github.com/getsentry/react-native-sentry/issues/124
I will reopen this and look at it now.

**Comment by HazAT** [comment] 2017-07-05 13:31
I've created a new release `0.14.2` with some minor fixes for android.
But, the core of the issue seems unresolved, it seems it's a problem with react-native itself:
https://github.com/facebook/react-native/issues/6946
The sourcemaps for android are wrong.

**Comment by benhowes** [comment] 2017-07-14 16:12
Hi @HazAT,

I've been investigating this since we're hitting it too. I'm not sure that the problem is with the source mapping, because that's done server side right? [The code here] (https://github.com/getsentry/react-native-sentry/blob/cb5f08fe9edaaf865b2ba5b289b768ed95cff6d1/android/src/main/java/io/sentry/RNSentryModule.java#L344) suggests that RN-sentry on the device is sending the native-codes after not finding the location of methods on the device, way before the source mapping stage.

I'm still investigating, though of course mapping function names and locations will be really helpful for us. 

Finally, this is only seen on Android for us, works great on iOS now!

**Comment by mitsuhiko** [comment] 2017-07-25 07:37
@benhowes it seems like that there are general problems with the quality of sourcemaps in React native in some situations unfortunately. I recommend opening issues against react-native in addition to here to get more eyes on this issue.

**Comment by HazAT** [comment] 2017-08-22 23:43
I will close this issue for now since there is nothing more we can do here currently.
We will soon ship some features on the server which overall should improve how we render `[native code]` and javascript stacktraces on the server.

**Closed by HazAT** 2017-08-22 23:43 UTC
