### ISSUE TITLE
Red screen error on Android shows Java stacktrace (instead of Javascript)

### ISSUE THREAD

**Issue by mmarvick** [getsentry/react-native-sentry#207] opened 2017-08-26 10:37 UTC
_Platform:_
- [ ]  iOS
- [X]  Android

Output of `npm ls --prod --depth=0`

```
├── axios@0.16.2
├── immutable@3.8.1
├── lodash@4.17.4
├── moment@2.18.1
├── native-base@2.3.1
├── react@16.0.0-alpha.12
├── react-native@0.46.4
├── react-native-datepicker@1.5.1
├── react-native-maps@0.15.3
├── react-native-picker@4.0.19
├── react-native-sentry@0.20.0
├── react-navigation@1.0.0-beta.11
├── react-redux@5.0.5
├── redux@3.6.0
├── redux-actions@2.0.3
├── redux-logger@3.0.6
├── redux-thunk@2.2.0
└── url@0.11.0

npm ERR! missing: react-native-drawer@git+https://github.com/GeekyAnts/react-native-drawer.git, required by native-base@2.3.1
npm ERR! missing: react-native-keyboard-aware-scroll-view@git+https://github.com/GeekyAnts/react-native-keyboard-aware-scroll-view.git, required by native-base@2.3.1
```

Config:

```
Sentry.config("https://secret@sentry.io/208153").install();
```

---
When I force a crash in the render method of a component, I get a Java stacktrace and error message instead of a Javascript one. This only happens after I've installed the `react-native-sentry` library, and I don't have this issue on iOS.

If I look in the debug log, I get the Javascript error message.

If I log into Sentry, I also get the Javascript error message, as I'd expect to. I'm not getting the correct Javascript stack trace yet, but I think this is just due to an issue with my source map, and not due to any issue with the library.

So it appears that this bug is only impacting the error being shown on the red screen in the app, and doesn't have any impact on what's being shown in the debugger or uploaded to Sentry.

**Steps to reproduce:**
Force a crash in the `render()` method of a component by calling some property on an undefined object (e.g. `console.log({}.a.b);`)

**Actual result:**
I get a crash screen with a java stacktrace.

![screenshot_1503741713](https://user-images.githubusercontent.com/3861298/29740541-6579e438-8a8b-11e7-9fd0-a5a2df29a8ce.png)

**Expected result:**
I get a crash screen with a javascript stacktrace. When I remove Sentry, this is the behavior I get. I get this behavior if I revert to a commit before Sentry was linked, but I also get this behavior if I just comment out the `Sentry.config()` call. So it looks like just having the library installed and linked in Gradle isn't an issue, but actually calling in to instantiate it is.

![screenshot_1503743432](https://user-images.githubusercontent.com/3861298/29740607-da28fb4c-8a8c-11e7-8a36-6fd37d4d5005.png)

**Comment by HazAT** [comment] 2017-08-28 06:41
Hey, I'm not able to reproduce this.
I've tested it with our example project:
https://github.com/getsentry/examples/tree/master/react-native
And it works as expected.

**Comment by HazAT** [comment] 2017-09-19 12:51
There must be something wrong with the integration of react-native-sentry into your android project. I will close this for now, if you are still having troubles feel free to post again.

**Closed by HazAT** 2017-09-19 12:51 UTC
